### ISSUE TITLE
Right arrow doesn't get disabled

### ISSUE THREAD

**Issue by ajitkspyt** [LucasLazaro/bootstrap-nav-tab-scrollable#2]
Hey. Great Plugin. Works very well.

But, I came across a small issue. The Left arrow gets disabled when you scroll to the extreme left. But the same won't happen to the right arrow when you scroll to the extreme right. Any idea why?

**Comment by LucasLazaro** [comment]
@ajitkspyt Hi! Sorry for the long delay, I have been away for a while. I'm pretty sure the problem occurs on the `updateArrowStyle`, I'll take a look and get back to you.

**Comment by LucasLazaro** [comment]
@ajitkspyt Silly problem involving resizing the viewport, probably fixed with [this commit](https://github.com/LucasLazaro/bootstrap-nav-tab-scrollable/commit/8314626e05cd2fe51c6e9aa46a9dda6372dec6b8?L=11#diff-6816137d1500d3a10dc266332e0197e5R11)
